spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 15ffbbe2ef214a4f4a5bcf38219d6f08
          google:
            client-secret: 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
          naver:
            client-secret: 8jHaZCFbq4
  mail:
    password: lhqfwzmkcsmtwgcp
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname